# Generated by Django 5.0.7 on 2024-08-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_banner_product_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='subcategories/'),
        ),
    ]
