# Generated by Django 5.0.7 on 2024-07-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_product_cartitem_order_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
