# Generated by Django 5.0.7 on 2024-08-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
