# Generated by Django 5.0.7 on 2024-08-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0005_remove_banner_description_remove_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='autumn',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='product',
            name='rainy',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='product',
            name='summer',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='product',
            name='winter',
            field=models.BooleanField(default='False'),
        ),
    ]
