# Generated by Django 5.0.7 on 2024-08-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0009_rename_is_activity_banner_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='which',
            field=models.CharField(choices=[('A', 'Angular'), ('F', 'Flutter')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
