# Generated by Django 5.0.7 on 2024-08-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0013_alter_banner_is_active_alter_cart_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='fashion.category'),
        ),
    ]
