# Generated by Django 5.0.7 on 2024-08-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0020_product_genders_product_heights_product_skin_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('NO_RETURN', 'No Return'), ('PENDING', 'Return Pending'), ('APPROVED', 'Return Approved'), ('REJECTED', 'Return Rejected')], default='NO_RETURN', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_requested_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
