# Generated by Django 5.0.7 on 2024-08-12 04:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0022_remove_order_refund_amount_remove_order_refund_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('required_men_dresses', models.IntegerField(default=0)),
                ('required_women_dresses', models.IntegerField(default=0)),
                ('required_kids_dresses', models.IntegerField(default=0)),
                ('fulfilled_men_dresses', models.IntegerField(default=0)),
                ('fulfilled_women_dresses', models.IntegerField(default=0)),
                ('fulfilled_kids_dresses', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disasters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DressDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_dresses', models.IntegerField(default=0)),
                ('women_dresses', models.IntegerField(default=0)),
                ('kids_dresses', models.IntegerField(default=0)),
                ('images', models.ImageField(null=True, upload_to='donations/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='fashion.disaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
