# Generated by Django 5.0.7 on 2024-08-12 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0023_disaster_dressdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donation_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='disaster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disasters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='dressdonation',
            name='images',
        ),
        migrations.AddField(
            model_name='dressdonation',
            name='images',
            field=models.ManyToManyField(related_name='donations', to='fashion.imageuploadmodel'),
        ),
    ]
