# Generated by Django 5.0.7 on 2024-08-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0036_alter_product_autumn_alter_product_is_trending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genders',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='heights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='usages',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
