# Generated by Django 5.0.7 on 2024-08-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0037_remove_product_genders_product_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gender',
            new_name='genders',
        ),
    ]
