# Generated by Django 5.0.7 on 2024-08-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0038_rename_gender_product_genders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
