# Generated by Django 5.0.7 on 2024-08-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0040_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
