# Generated by Django 5.0.7 on 2024-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0045_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
