# Generated by Django 5.0.7 on 2024-09-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0048_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
